<?php

use App\Custom\Active\ActiveForm;
?>

@extends('masters.main')

@section('title', 'Create new genre')



@section('content')
    <div class="row">
        <div class="panel panel-success">
            <div class="panel-heading">
                <h3 class="panel-title">Create new user</h3>
            </div>
            <div class="panel-body">
                <?php
                $form = ActiveForm::begin(false, 'post', [
                        "class" => "form-horizontal"
                ])
                ?>
                <div class='row'>
                    <div class="col-md-6 col-md-offset-3">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Name</label>

                            <div class="col-sm-8">
                                <?=
                                $form->textInput($genre, 'name', $errors, old(), [
                                        'class' => 'form-control',
                                        'placeholder' => 'Type  name...'
                                ])
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class='row'>
                    <div class="col-md-6 col-md-offset-3">
                        <div class="form-group">
                            <label class="col-sm-3 control-label">Alias</label>

                            <div class="col-sm-8">
                                <?=
                                $form->aliasInput($genre, 'alias', $errors, old(), [
                                        'class' => 'form-control',
                                        'placeholder' => 'Alias automatically generated by name...',
                                        'disabled' => true
                                ])
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
                <hr>
                <div class='row'>
                    <div class="col-sm-4 col-sm-offset-4">
                        <?=
                        $form->submitButton('Create genre', [
                                "class" => "btn btn-quirk btn-success btn-block"
                        ])
                        ?>
                    </div>
                </div>
                <?php ActiveForm::end() ?>
            </div>
        </div>

    </div>

@stop

